version: '3.7'

services:
  mysql:
    image: mysql:innovation
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: America/Bogota
    ports:
      - "9010:3306"
    